#
# Vivado (TM) v2015.2 (64-bit)
#
# re-create-project.tcl: Tcl script for re-creating project 'chip2chip_v1'
#
# Generated by Vivado on Tue Oct 02 15:24:04 BST 2018
# IP Build 1264090 on Wed Jun 24 14:22:01 MDT 2015
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (re-create-project.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "/aeg_sw/work/users/aod62/chip2chip_v1_working_mig/chip2chip_v1.srcs/sources_1/bd/c2c_top/c2c_top.bd"
#    "/aeg_sw/work/users/aod62/chip2chip_v1_working_mig/chip2chip_v1.srcs/sources_1/bd/c2c_top/ip/c2c_top_mig_7series_0_0/mig_a.prj"
#    "/aeg_sw/work/users/aod62/chip2chip_v1_working_mig/chip2chip_v1.srcs/sources_1/bd/c2c_top/ip/c2c_top_mig_7series_0_0/mig_b.prj"
#    "/aeg_sw/work/users/aod62/chip2chip_v1_working_mig/bram.coe"
#    "/aeg_sw/work/users/aod62/chip2chip_v1_working_mig/chip2chip_v1.srcs/sources_1/bd/c2c_top/hdl/c2c_top_wrapper.vhd"
#    "/aeg_sw/work/users/aod62/chip2chip_v1_working_mig/chip2chip_v1.srcs/constrs_1/new/c2c_constraints.xdc"
#
# 3. The following remote source files that were added to the original project:-
#
#    <none>
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/"]"

# Create project
create_project chip2chip_v1 ./chip2chip_v1

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [get_projects chip2chip_v1]
set_property "default_lib" "xil_defaultlib" $obj
set_property "part" "xc7vx690tffg1930-2" $obj
set_property "simulator_language" "Mixed" $obj
set_property "source_mgmt_mode" "DisplayOnly" $obj
set_property "target_language" "VHDL" $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/src/mig_a.prj"]"\
 "[file normalize "$origin_dir/src/mig_b.prj"]"\
 "[file normalize "$origin_dir/src/bram.coe"]"\
 "[file normalize "$origin_dir/src/c2c_top_wrapper.vhd"]"\
]

add_files -norecurse -fileset $obj $files

# Import local files from the original project
#set files [list \
# "[file normalize "$origin_dir/src/mig_a.prj"]"\
# "[file normalize "$origin_dir/src/mig_b.prj"]"\
# "[file normalize "$origin_dir/src/bram.coe"]"\
# "[file normalize "$origin_dir/src/c2c_top_wrapper.vhd"]"\
#]
#set imported_files [import_files -fileset sources_1 $files]


# Set 'sources_1' fileset file properties for remote files
# None


source ./scripts/re-create-bd.tcl


# Set 'sources_1' fileset file properties for local files
set file "c2c_top/c2c_top.bd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
if { ![get_property "is_locked" $file_obj] } {
  set_property "generate_synth_checkpoint" "0" $file_obj
}

#set file "hdl/c2c_top_wrapper.vhd"
#set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#set_property "file_type" "VHDL" $file_obj


# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property "top" "c2c_top_wrapper" $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
#set file "[file normalize "$origin_dir/src/c2c_constraints.xdc"]"
#set file_imported [import_files -fileset constrs_1 $file]
#set file "src/c2c_constraints.xdc"
#set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
#set_property "file_type" "XDC" $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property "target_constrs_file" "$origin_dir/src/c2c_constraints.xdc" $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property "xsim.compile.xvhdl.nosort" "1" $obj
set_property "xelab.unifast" "" $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
  create_run -name synth_1 -part xc7vx690tffg1930-2 -flow {Vivado Synthesis 2015} -strategy "Vivado Synthesis Defaults" -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2015" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property "part" "xc7vx690tffg1930-2" $obj



# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
  create_run -name impl_1 -part xc7vx690tffg1930-2 -flow {Vivado Implementation 2015} -strategy "Vivado Implementation Defaults" -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2015" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property "part" "xc7vx690tffg1930-2" $obj
set_property "steps.write_bitstream.args.bin_file" "1" $obj
set_property "steps.write_bitstream.args.readback_file" "0" $obj
set_property "steps.write_bitstream.args.verbose" "0" $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:chip2chip_v1"
