##################################################################################################
## 
##  Xilinx, Inc. 2010            www.xilinx.com 
##  Wed Oct 3 17:17:17 2018
##  Generated by MIG Version 2.3
##  
##################################################################################################
##  File name :       example_top.sdc
##  Details :     Constraints file
##                    FPGA Family:       VIRTEX7
##                    FPGA Part:         XC7VX980TFFG1930_PKG
##                    Speedgrade:        -2
##                    Design Entry:      VERILOG
##                    Frequency:         0 MHz
##                    Time Period:       1250 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR3_SDRAM->SODIMMs->MT8K51264HZ-13ADD
## Data Width: 64
## Time Period: 1250
## Data Mask: 1
##################################################################################################

create_clock -period 2 [get_ports sys_clk_p]

#create_clock -period 5 [get_ports clk_ref_i]

############## NET - IOSTANDARD ##################


