# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx690tffg1930-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /scratch/qem/adam/development/fem-ii-embedded-system/Femii_V7_Reference_Design/chip2chip_v1/chip2chip_v1.cache/wt [current_project]
set_property parent.project_path /scratch/qem/adam/development/fem-ii-embedded-system/Femii_V7_Reference_Design/chip2chip_v1/chip2chip_v1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
add_files /scratch/qem/adam/development/fem-ii-embedded-system/Femii_V7_Reference_Design/src/bram.coe
add_files /scratch/qem/adam/development/fem-ii-embedded-system/Femii_V7_Reference_Design/chip2chip_v1/chip2chip_v1.srcs/sources_1/bd/c2c_top/c2c_top.bd
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Femii_V7_Reference_Design/chip2chip_v1/chip2chip_v1.srcs/sources_1/bd/c2c_top/ip/c2c_top_axi_bram_ctrl_0_0/c2c_top_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Femii_V7_Reference_Design/chip2chip_v1/chip2chip_v1.srcs/sources_1/bd/c2c_top/ip/c2c_top_axi_bram_ctrl_0_bram_0/c2c_top_axi_bram_ctrl_0_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Femii_V7_Reference_Design/chip2chip_v1/chip2chip_v1.srcs/sources_1/bd/c2c_top/ip/c2c_top_axi_chip2chip_0_0/c2c_top_axi_chip2chip_0_0.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Femii_V7_Reference_Design/chip2chip_v1/chip2chip_v1.srcs/sources_1/bd/c2c_top/ip/c2c_top_axi_chip2chip_0_0/c2c_top_axi_chip2chip_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Femii_V7_Reference_Design/chip2chip_v1/chip2chip_v1.srcs/sources_1/bd/c2c_top/ip/c2c_top_axi_chip2chip_0_0/c2c_top_axi_chip2chip_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Femii_V7_Reference_Design/chip2chip_v1/chip2chip_v1.srcs/sources_1/bd/c2c_top/ip/c2c_top_xbar_0/c2c_top_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Femii_V7_Reference_Design/chip2chip_v1/chip2chip_v1.srcs/sources_1/bd/c2c_top/ip/c2c_top_axi_quad_spi_0_0/c2c_top_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Femii_V7_Reference_Design/chip2chip_v1/chip2chip_v1.srcs/sources_1/bd/c2c_top/ip/c2c_top_axi_quad_spi_0_0/c2c_top_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Femii_V7_Reference_Design/chip2chip_v1/chip2chip_v1.srcs/sources_1/bd/c2c_top/ip/c2c_top_axi_quad_spi_0_0/c2c_top_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Femii_V7_Reference_Design/chip2chip_v1/chip2chip_v1.srcs/sources_1/bd/c2c_top/ip/c2c_top_axi_quad_spi_0_0/c2c_top_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Femii_V7_Reference_Design/chip2chip_v1/chip2chip_v1.srcs/sources_1/bd/c2c_top/ip/c2c_top_clk_wiz_0_0/c2c_top_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Femii_V7_Reference_Design/chip2chip_v1/chip2chip_v1.srcs/sources_1/bd/c2c_top/ip/c2c_top_clk_wiz_0_0/c2c_top_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Femii_V7_Reference_Design/chip2chip_v1/chip2chip_v1.srcs/sources_1/bd/c2c_top/ip/c2c_top_clk_wiz_0_0/c2c_top_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Femii_V7_Reference_Design/chip2chip_v1/chip2chip_v1.srcs/sources_1/bd/c2c_top/ip/c2c_top_mig_7series_0_0/c2c_top_mig_7series_0_0/user_design/constraints/c2c_top_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Femii_V7_Reference_Design/chip2chip_v1/chip2chip_v1.srcs/sources_1/bd/c2c_top/ip/c2c_top_mig_7series_0_0/c2c_top_mig_7series_0_0/user_design/constraints/c2c_top_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Femii_V7_Reference_Design/chip2chip_v1/chip2chip_v1.srcs/sources_1/bd/c2c_top/ip/c2c_top_page_reg_0/c2c_top_page_reg_0_board.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Femii_V7_Reference_Design/chip2chip_v1/chip2chip_v1.srcs/sources_1/bd/c2c_top/ip/c2c_top_page_reg_0/c2c_top_page_reg_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Femii_V7_Reference_Design/chip2chip_v1/chip2chip_v1.srcs/sources_1/bd/c2c_top/ip/c2c_top_page_reg_0/c2c_top_page_reg_0.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Femii_V7_Reference_Design/chip2chip_v1/chip2chip_v1.srcs/sources_1/bd/c2c_top/ip/c2c_top_rst_mig_7series_0_200M_0/c2c_top_rst_mig_7series_0_200M_0_board.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Femii_V7_Reference_Design/chip2chip_v1/chip2chip_v1.srcs/sources_1/bd/c2c_top/ip/c2c_top_rst_mig_7series_0_200M_0/c2c_top_rst_mig_7series_0_200M_0.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Femii_V7_Reference_Design/chip2chip_v1/chip2chip_v1.srcs/sources_1/bd/c2c_top/ip/c2c_top_rst_mig_7series_0_200M_0/c2c_top_rst_mig_7series_0_200M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Femii_V7_Reference_Design/chip2chip_v1/chip2chip_v1.srcs/sources_1/bd/c2c_top/ip/c2c_top_status_control_0/c2c_top_status_control_0_board.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Femii_V7_Reference_Design/chip2chip_v1/chip2chip_v1.srcs/sources_1/bd/c2c_top/ip/c2c_top_status_control_0/c2c_top_status_control_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Femii_V7_Reference_Design/chip2chip_v1/chip2chip_v1.srcs/sources_1/bd/c2c_top/ip/c2c_top_status_control_0/c2c_top_status_control_0.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Femii_V7_Reference_Design/chip2chip_v1/chip2chip_v1.srcs/sources_1/bd/c2c_top/ip/c2c_top_version_reg_0/c2c_top_version_reg_0_board.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Femii_V7_Reference_Design/chip2chip_v1/chip2chip_v1.srcs/sources_1/bd/c2c_top/ip/c2c_top_version_reg_0/c2c_top_version_reg_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Femii_V7_Reference_Design/chip2chip_v1/chip2chip_v1.srcs/sources_1/bd/c2c_top/ip/c2c_top_version_reg_0/c2c_top_version_reg_0.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Femii_V7_Reference_Design/chip2chip_v1/chip2chip_v1.srcs/sources_1/bd/c2c_top/ip/c2c_top_auto_pc_0/c2c_top_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Femii_V7_Reference_Design/chip2chip_v1/chip2chip_v1.srcs/sources_1/bd/c2c_top/ip/c2c_top_auto_pc_1/c2c_top_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Femii_V7_Reference_Design/chip2chip_v1/chip2chip_v1.srcs/sources_1/bd/c2c_top/ip/c2c_top_auto_pc_2/c2c_top_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Femii_V7_Reference_Design/chip2chip_v1/chip2chip_v1.srcs/sources_1/bd/c2c_top/ip/c2c_top_auto_pc_3/c2c_top_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Femii_V7_Reference_Design/chip2chip_v1/chip2chip_v1.srcs/sources_1/bd/c2c_top/c2c_top_ooc.xdc]
set_property is_locked true [get_files /scratch/qem/adam/development/fem-ii-embedded-system/Femii_V7_Reference_Design/chip2chip_v1/chip2chip_v1.srcs/sources_1/bd/c2c_top/c2c_top.bd]

read_vhdl -library xil_defaultlib /scratch/qem/adam/development/fem-ii-embedded-system/Femii_V7_Reference_Design/src/c2c_top_wrapper.vhd
read_xdc /scratch/qem/adam/development/fem-ii-embedded-system/Femii_V7_Reference_Design/src/c2c_constraints.xdc
set_property used_in_implementation false [get_files /scratch/qem/adam/development/fem-ii-embedded-system/Femii_V7_Reference_Design/src/c2c_constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top c2c_top_wrapper -part xc7vx690tffg1930-2
write_checkpoint -noxdef c2c_top_wrapper.dcp
catch { report_utilization -file c2c_top_wrapper_utilization_synth.rpt -pb c2c_top_wrapper_utilization_synth.pb }
