# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /scratch/qem/adam/development/fem-ii-embedded-system/Femii_V7_Reference_Design/src/c2c_constraints.xdc

# Block Designs: bd/c2c_top/c2c_top.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c2c_top || ORIG_REF_NAME==c2c_top}]

# IP: bd/c2c_top/ip/c2c_top_axi_bram_ctrl_0_0/c2c_top_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c2c_top_axi_bram_ctrl_0_0 || ORIG_REF_NAME==c2c_top_axi_bram_ctrl_0_0}]

# IP: bd/c2c_top/ip/c2c_top_axi_bram_ctrl_0_bram_0/c2c_top_axi_bram_ctrl_0_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c2c_top_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==c2c_top_axi_bram_ctrl_0_bram_0}]

# IP: bd/c2c_top/ip/c2c_top_axi_chip2chip_0_0/c2c_top_axi_chip2chip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c2c_top_axi_chip2chip_0_0 || ORIG_REF_NAME==c2c_top_axi_chip2chip_0_0}]

# IP: bd/c2c_top/ip/c2c_top_axi_interconnect_0_0/c2c_top_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c2c_top_axi_interconnect_0_0 || ORIG_REF_NAME==c2c_top_axi_interconnect_0_0}]

# IP: bd/c2c_top/ip/c2c_top_xbar_0/c2c_top_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c2c_top_xbar_0 || ORIG_REF_NAME==c2c_top_xbar_0}]

# IP: bd/c2c_top/ip/c2c_top_axi_quad_spi_0_0/c2c_top_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c2c_top_axi_quad_spi_0_0 || ORIG_REF_NAME==c2c_top_axi_quad_spi_0_0}]

# IP: bd/c2c_top/ip/c2c_top_clk_wiz_0_0/c2c_top_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c2c_top_clk_wiz_0_0 || ORIG_REF_NAME==c2c_top_clk_wiz_0_0}]

# IP: bd/c2c_top/ip/c2c_top_mig_7series_0_0/c2c_top_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c2c_top_mig_7series_0_0 || ORIG_REF_NAME==c2c_top_mig_7series_0_0}]

# IP: bd/c2c_top/ip/c2c_top_page_reg_0/c2c_top_page_reg_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c2c_top_page_reg_0 || ORIG_REF_NAME==c2c_top_page_reg_0}]

# IP: bd/c2c_top/ip/c2c_top_rst_mig_7series_0_200M_0/c2c_top_rst_mig_7series_0_200M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c2c_top_rst_mig_7series_0_200M_0 || ORIG_REF_NAME==c2c_top_rst_mig_7series_0_200M_0}]

# IP: bd/c2c_top/ip/c2c_top_status_control_0/c2c_top_status_control_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c2c_top_status_control_0 || ORIG_REF_NAME==c2c_top_status_control_0}]

# IP: bd/c2c_top/ip/c2c_top_version_reg_0/c2c_top_version_reg_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c2c_top_version_reg_0 || ORIG_REF_NAME==c2c_top_version_reg_0}]

# IP: bd/c2c_top/ip/c2c_top_xlconcat_0_0/c2c_top_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c2c_top_xlconcat_0_0 || ORIG_REF_NAME==c2c_top_xlconcat_0_0}]

# IP: bd/c2c_top/ip/c2c_top_xlconstant_0_0/c2c_top_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c2c_top_xlconstant_0_0 || ORIG_REF_NAME==c2c_top_xlconstant_0_0}]

# IP: bd/c2c_top/ip/c2c_top_xlconstant_1_0/c2c_top_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c2c_top_xlconstant_1_0 || ORIG_REF_NAME==c2c_top_xlconstant_1_0}]

# IP: bd/c2c_top/ip/c2c_top_xlconstant_2_0/c2c_top_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c2c_top_xlconstant_2_0 || ORIG_REF_NAME==c2c_top_xlconstant_2_0}]

# IP: bd/c2c_top/ip/c2c_top_xlconstant_3_0/c2c_top_xlconstant_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c2c_top_xlconstant_3_0 || ORIG_REF_NAME==c2c_top_xlconstant_3_0}]

# IP: bd/c2c_top/ip/c2c_top_xlslice_0_0/c2c_top_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c2c_top_xlslice_0_0 || ORIG_REF_NAME==c2c_top_xlslice_0_0}]

# IP: bd/c2c_top/ip/c2c_top_xlslice_1_0/c2c_top_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c2c_top_xlslice_1_0 || ORIG_REF_NAME==c2c_top_xlslice_1_0}]

# IP: bd/c2c_top/ip/c2c_top_auto_pc_0/c2c_top_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c2c_top_auto_pc_0 || ORIG_REF_NAME==c2c_top_auto_pc_0}]

# IP: bd/c2c_top/ip/c2c_top_auto_pc_1/c2c_top_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c2c_top_auto_pc_1 || ORIG_REF_NAME==c2c_top_auto_pc_1}]

# IP: bd/c2c_top/ip/c2c_top_auto_pc_2/c2c_top_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c2c_top_auto_pc_2 || ORIG_REF_NAME==c2c_top_auto_pc_2}]

# IP: bd/c2c_top/ip/c2c_top_auto_pc_3/c2c_top_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c2c_top_auto_pc_3 || ORIG_REF_NAME==c2c_top_auto_pc_3}]

# XDC: bd/c2c_top/ip/c2c_top_axi_bram_ctrl_0_0/c2c_top_axi_bram_ctrl_0_0_ooc.xdc

# XDC: bd/c2c_top/ip/c2c_top_axi_bram_ctrl_0_bram_0/c2c_top_axi_bram_ctrl_0_bram_0_ooc.xdc

# XDC: bd/c2c_top/ip/c2c_top_axi_chip2chip_0_0/c2c_top_axi_chip2chip_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==c2c_top_axi_chip2chip_0_0 || ORIG_REF_NAME==c2c_top_axi_chip2chip_0_0}] {/inst }]/inst ]]

# XDC: bd/c2c_top/ip/c2c_top_axi_chip2chip_0_0/c2c_top_axi_chip2chip_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==c2c_top_axi_chip2chip_0_0 || ORIG_REF_NAME==c2c_top_axi_chip2chip_0_0}] {/inst }]/inst ]]

# XDC: bd/c2c_top/ip/c2c_top_axi_chip2chip_0_0/c2c_top_axi_chip2chip_0_0_ooc.xdc

# XDC: bd/c2c_top/ip/c2c_top_xbar_0/c2c_top_xbar_0_ooc.xdc

# XDC: bd/c2c_top/ip/c2c_top_axi_quad_spi_0_0/c2c_top_axi_quad_spi_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==c2c_top_axi_quad_spi_0_0 || ORIG_REF_NAME==c2c_top_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/c2c_top/ip/c2c_top_axi_quad_spi_0_0/c2c_top_axi_quad_spi_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==c2c_top_axi_quad_spi_0_0 || ORIG_REF_NAME==c2c_top_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/c2c_top/ip/c2c_top_axi_quad_spi_0_0/c2c_top_axi_quad_spi_0_0_ooc.xdc

# XDC: bd/c2c_top/ip/c2c_top_axi_quad_spi_0_0/c2c_top_axi_quad_spi_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==c2c_top_axi_quad_spi_0_0 || ORIG_REF_NAME==c2c_top_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/c2c_top/ip/c2c_top_clk_wiz_0_0/c2c_top_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==c2c_top_clk_wiz_0_0 || ORIG_REF_NAME==c2c_top_clk_wiz_0_0}] {/U0 }]/U0 ]]

# XDC: bd/c2c_top/ip/c2c_top_clk_wiz_0_0/c2c_top_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==c2c_top_clk_wiz_0_0 || ORIG_REF_NAME==c2c_top_clk_wiz_0_0}] {/U0 }]/U0 ]]

# XDC: bd/c2c_top/ip/c2c_top_clk_wiz_0_0/c2c_top_clk_wiz_0_0_ooc.xdc

# XDC: bd/c2c_top/ip/c2c_top_mig_7series_0_0/c2c_top_mig_7series_0_0/user_design/constraints/c2c_top_mig_7series_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c2c_top_mig_7series_0_0 || ORIG_REF_NAME==c2c_top_mig_7series_0_0}]

# XDC: bd/c2c_top/ip/c2c_top_mig_7series_0_0/c2c_top_mig_7series_0_0/user_design/constraints/c2c_top_mig_7series_0_0_ooc.xdc

# XDC: bd/c2c_top/ip/c2c_top_page_reg_0/c2c_top_page_reg_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==c2c_top_page_reg_0 || ORIG_REF_NAME==c2c_top_page_reg_0}] {/U0 }]/U0 ]]

# XDC: bd/c2c_top/ip/c2c_top_page_reg_0/c2c_top_page_reg_0_ooc.xdc

# XDC: bd/c2c_top/ip/c2c_top_page_reg_0/c2c_top_page_reg_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==c2c_top_page_reg_0 || ORIG_REF_NAME==c2c_top_page_reg_0}] {/U0 }]/U0 ]]

# XDC: bd/c2c_top/ip/c2c_top_rst_mig_7series_0_200M_0/c2c_top_rst_mig_7series_0_200M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c2c_top_rst_mig_7series_0_200M_0 || ORIG_REF_NAME==c2c_top_rst_mig_7series_0_200M_0}]

# XDC: bd/c2c_top/ip/c2c_top_rst_mig_7series_0_200M_0/c2c_top_rst_mig_7series_0_200M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c2c_top_rst_mig_7series_0_200M_0 || ORIG_REF_NAME==c2c_top_rst_mig_7series_0_200M_0}]

# XDC: bd/c2c_top/ip/c2c_top_rst_mig_7series_0_200M_0/c2c_top_rst_mig_7series_0_200M_0_ooc.xdc

# XDC: bd/c2c_top/ip/c2c_top_status_control_0/c2c_top_status_control_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==c2c_top_status_control_0 || ORIG_REF_NAME==c2c_top_status_control_0}] {/U0 }]/U0 ]]

# XDC: bd/c2c_top/ip/c2c_top_status_control_0/c2c_top_status_control_0_ooc.xdc

# XDC: bd/c2c_top/ip/c2c_top_status_control_0/c2c_top_status_control_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==c2c_top_status_control_0 || ORIG_REF_NAME==c2c_top_status_control_0}] {/U0 }]/U0 ]]

# XDC: bd/c2c_top/ip/c2c_top_version_reg_0/c2c_top_version_reg_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==c2c_top_version_reg_0 || ORIG_REF_NAME==c2c_top_version_reg_0}] {/U0 }]/U0 ]]

# XDC: bd/c2c_top/ip/c2c_top_version_reg_0/c2c_top_version_reg_0_ooc.xdc

# XDC: bd/c2c_top/ip/c2c_top_version_reg_0/c2c_top_version_reg_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==c2c_top_version_reg_0 || ORIG_REF_NAME==c2c_top_version_reg_0}] {/U0 }]/U0 ]]

# XDC: bd/c2c_top/ip/c2c_top_auto_pc_0/c2c_top_auto_pc_0_ooc.xdc

# XDC: bd/c2c_top/ip/c2c_top_auto_pc_1/c2c_top_auto_pc_1_ooc.xdc

# XDC: bd/c2c_top/ip/c2c_top_auto_pc_2/c2c_top_auto_pc_2_ooc.xdc

# XDC: bd/c2c_top/ip/c2c_top_auto_pc_3/c2c_top_auto_pc_3_ooc.xdc

# XDC: bd/c2c_top/c2c_top_ooc.xdc
