#!/bin/sh
#
# Start the QEM server
#

start() {
	printf "Starting the server: "
	cd /root
	sh qem.sh &
	echo "OK"
}

stop() {
	printf "Stopping the QEM server "
	killproc qem.sh
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
