# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /scratch/qem/adam/development/fem-ii-embedded-system/Mars_ZX3_Reference_Design_for_FEMII/src/MarsZX3_FEMII.xdc

# Block Designs: bd/MarsZX3/MarsZX3.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3 || ORIG_REF_NAME==MarsZX3}]

# IP: bd/MarsZX3/ip/MarsZX3_axi_bram_ctrl_0_0/MarsZX3_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_axi_bram_ctrl_0_0 || ORIG_REF_NAME==MarsZX3_axi_bram_ctrl_0_0}]

# IP: bd/MarsZX3/ip/MarsZX3_axi_chip2chip_0_0/MarsZX3_axi_chip2chip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_axi_chip2chip_0_0 || ORIG_REF_NAME==MarsZX3_axi_chip2chip_0_0}]

# IP: bd/MarsZX3/ip/MarsZX3_axi_gpio_0_0/MarsZX3_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_axi_gpio_0_0 || ORIG_REF_NAME==MarsZX3_axi_gpio_0_0}]

# IP: bd/MarsZX3/ip/MarsZX3_axi_interconnect_0_0/MarsZX3_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_axi_interconnect_0_0 || ORIG_REF_NAME==MarsZX3_axi_interconnect_0_0}]

# IP: bd/MarsZX3/ip/MarsZX3_axi_quad_spi_0_0/MarsZX3_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_axi_quad_spi_0_0 || ORIG_REF_NAME==MarsZX3_axi_quad_spi_0_0}]

# IP: bd/MarsZX3/ip/MarsZX3_blk_mem_gen_0_0/MarsZX3_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_blk_mem_gen_0_0 || ORIG_REF_NAME==MarsZX3_blk_mem_gen_0_0}]

# IP: bd/MarsZX3/ip/MarsZX3_processing_system7_0_0/MarsZX3_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_processing_system7_0_0 || ORIG_REF_NAME==MarsZX3_processing_system7_0_0}]

# IP: bd/MarsZX3/ip/MarsZX3_processing_system7_0_axi_periph_0/MarsZX3_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==MarsZX3_processing_system7_0_axi_periph_0}]

# IP: bd/MarsZX3/ip/MarsZX3_xbar_0/MarsZX3_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_xbar_0 || ORIG_REF_NAME==MarsZX3_xbar_0}]

# IP: bd/MarsZX3/ip/MarsZX3_reset_reg_0/MarsZX3_reset_reg_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_reset_reg_0 || ORIG_REF_NAME==MarsZX3_reset_reg_0}]

# IP: bd/MarsZX3/ip/MarsZX3_rst_processing_system7_0_50M_0/MarsZX3_rst_processing_system7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==MarsZX3_rst_processing_system7_0_50M_0}]

# IP: bd/MarsZX3/ip/MarsZX3_rst_processing_system7_0_50M1_0/MarsZX3_rst_processing_system7_0_50M1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_rst_processing_system7_0_50M1_0 || ORIG_REF_NAME==MarsZX3_rst_processing_system7_0_50M1_0}]

# IP: bd/MarsZX3/ip/MarsZX3_status_control_0/MarsZX3_status_control_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_status_control_0 || ORIG_REF_NAME==MarsZX3_status_control_0}]

# IP: bd/MarsZX3/ip/MarsZX3_xadc_wiz_0_0/MarsZX3_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_xadc_wiz_0_0 || ORIG_REF_NAME==MarsZX3_xadc_wiz_0_0}]

# IP: bd/MarsZX3/ip/MarsZX3_xlconcat_0_0/MarsZX3_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_xlconcat_0_0 || ORIG_REF_NAME==MarsZX3_xlconcat_0_0}]

# IP: bd/MarsZX3/ip/MarsZX3_xlconcat_1_0/MarsZX3_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_xlconcat_1_0 || ORIG_REF_NAME==MarsZX3_xlconcat_1_0}]

# IP: bd/MarsZX3/ip/MarsZX3_auto_pc_0/MarsZX3_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_auto_pc_0 || ORIG_REF_NAME==MarsZX3_auto_pc_0}]

# IP: bd/MarsZX3/ip/MarsZX3_auto_pc_1/MarsZX3_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_auto_pc_1 || ORIG_REF_NAME==MarsZX3_auto_pc_1}]

# IP: bd/MarsZX3/ip/MarsZX3_auto_pc_2/MarsZX3_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_auto_pc_2 || ORIG_REF_NAME==MarsZX3_auto_pc_2}]

# IP: bd/MarsZX3/ip/MarsZX3_auto_pc_3/MarsZX3_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_auto_pc_3 || ORIG_REF_NAME==MarsZX3_auto_pc_3}]

# IP: bd/MarsZX3/ip/MarsZX3_auto_pc_4/MarsZX3_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_auto_pc_4 || ORIG_REF_NAME==MarsZX3_auto_pc_4}]

# IP: bd/MarsZX3/ip/MarsZX3_auto_pc_5/MarsZX3_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_auto_pc_5 || ORIG_REF_NAME==MarsZX3_auto_pc_5}]

# IP: bd/MarsZX3/ip/MarsZX3_auto_pc_6/MarsZX3_auto_pc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_auto_pc_6 || ORIG_REF_NAME==MarsZX3_auto_pc_6}]

# XDC: bd/MarsZX3/ip/MarsZX3_axi_bram_ctrl_0_0/MarsZX3_axi_bram_ctrl_0_0_ooc.xdc

# XDC: bd/MarsZX3/ip/MarsZX3_axi_chip2chip_0_0/MarsZX3_axi_chip2chip_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MarsZX3_axi_chip2chip_0_0 || ORIG_REF_NAME==MarsZX3_axi_chip2chip_0_0}] {/inst }]/inst ]]

# XDC: bd/MarsZX3/ip/MarsZX3_axi_chip2chip_0_0/MarsZX3_axi_chip2chip_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MarsZX3_axi_chip2chip_0_0 || ORIG_REF_NAME==MarsZX3_axi_chip2chip_0_0}] {/inst }]/inst ]]

# XDC: bd/MarsZX3/ip/MarsZX3_axi_chip2chip_0_0/MarsZX3_axi_chip2chip_0_0_ooc.xdc

# XDC: bd/MarsZX3/ip/MarsZX3_axi_gpio_0_0/MarsZX3_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MarsZX3_axi_gpio_0_0 || ORIG_REF_NAME==MarsZX3_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/MarsZX3/ip/MarsZX3_axi_gpio_0_0/MarsZX3_axi_gpio_0_0_ooc.xdc

# XDC: bd/MarsZX3/ip/MarsZX3_axi_gpio_0_0/MarsZX3_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MarsZX3_axi_gpio_0_0 || ORIG_REF_NAME==MarsZX3_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/MarsZX3/ip/MarsZX3_axi_quad_spi_0_0/MarsZX3_axi_quad_spi_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MarsZX3_axi_quad_spi_0_0 || ORIG_REF_NAME==MarsZX3_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/MarsZX3/ip/MarsZX3_axi_quad_spi_0_0/MarsZX3_axi_quad_spi_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MarsZX3_axi_quad_spi_0_0 || ORIG_REF_NAME==MarsZX3_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/MarsZX3/ip/MarsZX3_axi_quad_spi_0_0/MarsZX3_axi_quad_spi_0_0_ooc.xdc

# XDC: bd/MarsZX3/ip/MarsZX3_axi_quad_spi_0_0/MarsZX3_axi_quad_spi_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MarsZX3_axi_quad_spi_0_0 || ORIG_REF_NAME==MarsZX3_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/MarsZX3/ip/MarsZX3_blk_mem_gen_0_0/MarsZX3_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/MarsZX3/ip/MarsZX3_processing_system7_0_0/MarsZX3_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MarsZX3_processing_system7_0_0 || ORIG_REF_NAME==MarsZX3_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/MarsZX3/ip/MarsZX3_xbar_0/MarsZX3_xbar_0_ooc.xdc

# XDC: bd/MarsZX3/ip/MarsZX3_reset_reg_0/MarsZX3_reset_reg_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MarsZX3_reset_reg_0 || ORIG_REF_NAME==MarsZX3_reset_reg_0}] {/U0 }]/U0 ]]

# XDC: bd/MarsZX3/ip/MarsZX3_reset_reg_0/MarsZX3_reset_reg_0_ooc.xdc

# XDC: bd/MarsZX3/ip/MarsZX3_reset_reg_0/MarsZX3_reset_reg_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MarsZX3_reset_reg_0 || ORIG_REF_NAME==MarsZX3_reset_reg_0}] {/U0 }]/U0 ]]

# XDC: bd/MarsZX3/ip/MarsZX3_rst_processing_system7_0_50M_0/MarsZX3_rst_processing_system7_0_50M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==MarsZX3_rst_processing_system7_0_50M_0}]

# XDC: bd/MarsZX3/ip/MarsZX3_rst_processing_system7_0_50M_0/MarsZX3_rst_processing_system7_0_50M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_rst_processing_system7_0_50M_0 || ORIG_REF_NAME==MarsZX3_rst_processing_system7_0_50M_0}]

# XDC: bd/MarsZX3/ip/MarsZX3_rst_processing_system7_0_50M_0/MarsZX3_rst_processing_system7_0_50M_0_ooc.xdc

# XDC: bd/MarsZX3/ip/MarsZX3_rst_processing_system7_0_50M1_0/MarsZX3_rst_processing_system7_0_50M1_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_rst_processing_system7_0_50M1_0 || ORIG_REF_NAME==MarsZX3_rst_processing_system7_0_50M1_0}]

# XDC: bd/MarsZX3/ip/MarsZX3_rst_processing_system7_0_50M1_0/MarsZX3_rst_processing_system7_0_50M1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MarsZX3_rst_processing_system7_0_50M1_0 || ORIG_REF_NAME==MarsZX3_rst_processing_system7_0_50M1_0}]

# XDC: bd/MarsZX3/ip/MarsZX3_rst_processing_system7_0_50M1_0/MarsZX3_rst_processing_system7_0_50M1_0_ooc.xdc

# XDC: bd/MarsZX3/ip/MarsZX3_status_control_0/MarsZX3_status_control_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MarsZX3_status_control_0 || ORIG_REF_NAME==MarsZX3_status_control_0}] {/U0 }]/U0 ]]

# XDC: bd/MarsZX3/ip/MarsZX3_status_control_0/MarsZX3_status_control_0_ooc.xdc

# XDC: bd/MarsZX3/ip/MarsZX3_status_control_0/MarsZX3_status_control_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MarsZX3_status_control_0 || ORIG_REF_NAME==MarsZX3_status_control_0}] {/U0 }]/U0 ]]

# XDC: bd/MarsZX3/ip/MarsZX3_xadc_wiz_0_0/MarsZX3_xadc_wiz_0_0_ooc.xdc

# XDC: bd/MarsZX3/ip/MarsZX3_xadc_wiz_0_0/MarsZX3_xadc_wiz_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MarsZX3_xadc_wiz_0_0 || ORIG_REF_NAME==MarsZX3_xadc_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/MarsZX3/ip/MarsZX3_auto_pc_0/MarsZX3_auto_pc_0_ooc.xdc

# XDC: bd/MarsZX3/ip/MarsZX3_auto_pc_1/MarsZX3_auto_pc_1_ooc.xdc

# XDC: bd/MarsZX3/ip/MarsZX3_auto_pc_2/MarsZX3_auto_pc_2_ooc.xdc

# XDC: bd/MarsZX3/ip/MarsZX3_auto_pc_3/MarsZX3_auto_pc_3_ooc.xdc

# XDC: bd/MarsZX3/ip/MarsZX3_auto_pc_4/MarsZX3_auto_pc_4_ooc.xdc

# XDC: bd/MarsZX3/ip/MarsZX3_auto_pc_5/MarsZX3_auto_pc_5_ooc.xdc

# XDC: bd/MarsZX3/ip/MarsZX3_auto_pc_6/MarsZX3_auto_pc_6_ooc.xdc

# XDC: bd/MarsZX3/MarsZX3_ooc.xdc
