# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /scratch/qem/adam/development/fem-ii-embedded-system/Mars_ZX3_Reference_Design_for_FEMII/Vivado_FEMII/MarsZX3_FEMII.cache/wt [current_project]
set_property parent.project_path /scratch/qem/adam/development/fem-ii-embedded-system/Mars_ZX3_Reference_Design_for_FEMII/Vivado_FEMII/MarsZX3_FEMII.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files /scratch/qem/adam/development/fem-ii-embedded-system/Mars_ZX3_Reference_Design_for_FEMII/Vivado_FEMII/MarsZX3_FEMII.srcs/sources_1/bd/MarsZX3/MarsZX3.bd
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Mars_ZX3_Reference_Design_for_FEMII/Vivado_FEMII/MarsZX3_FEMII.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_axi_bram_ctrl_0_0/MarsZX3_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Mars_ZX3_Reference_Design_for_FEMII/Vivado_FEMII/MarsZX3_FEMII.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_axi_chip2chip_0_0/MarsZX3_axi_chip2chip_0_0.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Mars_ZX3_Reference_Design_for_FEMII/Vivado_FEMII/MarsZX3_FEMII.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_axi_chip2chip_0_0/MarsZX3_axi_chip2chip_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Mars_ZX3_Reference_Design_for_FEMII/Vivado_FEMII/MarsZX3_FEMII.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_axi_chip2chip_0_0/MarsZX3_axi_chip2chip_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Mars_ZX3_Reference_Design_for_FEMII/Vivado_FEMII/MarsZX3_FEMII.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_axi_gpio_0_0/MarsZX3_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Mars_ZX3_Reference_Design_for_FEMII/Vivado_FEMII/MarsZX3_FEMII.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_axi_gpio_0_0/MarsZX3_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Mars_ZX3_Reference_Design_for_FEMII/Vivado_FEMII/MarsZX3_FEMII.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_axi_gpio_0_0/MarsZX3_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Mars_ZX3_Reference_Design_for_FEMII/Vivado_FEMII/MarsZX3_FEMII.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_axi_quad_spi_0_0/MarsZX3_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Mars_ZX3_Reference_Design_for_FEMII/Vivado_FEMII/MarsZX3_FEMII.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_axi_quad_spi_0_0/MarsZX3_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Mars_ZX3_Reference_Design_for_FEMII/Vivado_FEMII/MarsZX3_FEMII.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_axi_quad_spi_0_0/MarsZX3_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Mars_ZX3_Reference_Design_for_FEMII/Vivado_FEMII/MarsZX3_FEMII.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_axi_quad_spi_0_0/MarsZX3_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Mars_ZX3_Reference_Design_for_FEMII/Vivado_FEMII/MarsZX3_FEMII.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_blk_mem_gen_0_0/MarsZX3_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Mars_ZX3_Reference_Design_for_FEMII/Vivado_FEMII/MarsZX3_FEMII.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_processing_system7_0_0/MarsZX3_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Mars_ZX3_Reference_Design_for_FEMII/Vivado_FEMII/MarsZX3_FEMII.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_xbar_0/MarsZX3_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Mars_ZX3_Reference_Design_for_FEMII/Vivado_FEMII/MarsZX3_FEMII.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_reset_reg_0/MarsZX3_reset_reg_0_board.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Mars_ZX3_Reference_Design_for_FEMII/Vivado_FEMII/MarsZX3_FEMII.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_reset_reg_0/MarsZX3_reset_reg_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Mars_ZX3_Reference_Design_for_FEMII/Vivado_FEMII/MarsZX3_FEMII.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_reset_reg_0/MarsZX3_reset_reg_0.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Mars_ZX3_Reference_Design_for_FEMII/Vivado_FEMII/MarsZX3_FEMII.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_rst_processing_system7_0_50M_0/MarsZX3_rst_processing_system7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Mars_ZX3_Reference_Design_for_FEMII/Vivado_FEMII/MarsZX3_FEMII.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_rst_processing_system7_0_50M_0/MarsZX3_rst_processing_system7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Mars_ZX3_Reference_Design_for_FEMII/Vivado_FEMII/MarsZX3_FEMII.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_rst_processing_system7_0_50M_0/MarsZX3_rst_processing_system7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Mars_ZX3_Reference_Design_for_FEMII/Vivado_FEMII/MarsZX3_FEMII.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_rst_processing_system7_0_50M1_0/MarsZX3_rst_processing_system7_0_50M1_0_board.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Mars_ZX3_Reference_Design_for_FEMII/Vivado_FEMII/MarsZX3_FEMII.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_rst_processing_system7_0_50M1_0/MarsZX3_rst_processing_system7_0_50M1_0.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Mars_ZX3_Reference_Design_for_FEMII/Vivado_FEMII/MarsZX3_FEMII.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_rst_processing_system7_0_50M1_0/MarsZX3_rst_processing_system7_0_50M1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Mars_ZX3_Reference_Design_for_FEMII/Vivado_FEMII/MarsZX3_FEMII.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_status_control_0/MarsZX3_status_control_0_board.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Mars_ZX3_Reference_Design_for_FEMII/Vivado_FEMII/MarsZX3_FEMII.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_status_control_0/MarsZX3_status_control_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Mars_ZX3_Reference_Design_for_FEMII/Vivado_FEMII/MarsZX3_FEMII.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_status_control_0/MarsZX3_status_control_0.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Mars_ZX3_Reference_Design_for_FEMII/Vivado_FEMII/MarsZX3_FEMII.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_xadc_wiz_0_0/MarsZX3_xadc_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Mars_ZX3_Reference_Design_for_FEMII/Vivado_FEMII/MarsZX3_FEMII.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_xadc_wiz_0_0/MarsZX3_xadc_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Mars_ZX3_Reference_Design_for_FEMII/Vivado_FEMII/MarsZX3_FEMII.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_auto_pc_0/MarsZX3_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Mars_ZX3_Reference_Design_for_FEMII/Vivado_FEMII/MarsZX3_FEMII.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_auto_pc_1/MarsZX3_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Mars_ZX3_Reference_Design_for_FEMII/Vivado_FEMII/MarsZX3_FEMII.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_auto_pc_2/MarsZX3_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Mars_ZX3_Reference_Design_for_FEMII/Vivado_FEMII/MarsZX3_FEMII.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_auto_pc_3/MarsZX3_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Mars_ZX3_Reference_Design_for_FEMII/Vivado_FEMII/MarsZX3_FEMII.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_auto_pc_4/MarsZX3_auto_pc_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Mars_ZX3_Reference_Design_for_FEMII/Vivado_FEMII/MarsZX3_FEMII.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_auto_pc_5/MarsZX3_auto_pc_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Mars_ZX3_Reference_Design_for_FEMII/Vivado_FEMII/MarsZX3_FEMII.srcs/sources_1/bd/MarsZX3/ip/MarsZX3_auto_pc_6/MarsZX3_auto_pc_6_ooc.xdc]
set_property used_in_implementation false [get_files -all /scratch/qem/adam/development/fem-ii-embedded-system/Mars_ZX3_Reference_Design_for_FEMII/Vivado_FEMII/MarsZX3_FEMII.srcs/sources_1/bd/MarsZX3/MarsZX3_ooc.xdc]
set_property is_locked true [get_files /scratch/qem/adam/development/fem-ii-embedded-system/Mars_ZX3_Reference_Design_for_FEMII/Vivado_FEMII/MarsZX3_FEMII.srcs/sources_1/bd/MarsZX3/MarsZX3.bd]

read_vhdl -library xil_defaultlib /scratch/qem/adam/development/fem-ii-embedded-system/Mars_ZX3_Reference_Design_for_FEMII/src/system_top_FEMII.vhd
read_xdc /scratch/qem/adam/development/fem-ii-embedded-system/Mars_ZX3_Reference_Design_for_FEMII/src/MarsZX3_FEMII.xdc
set_property used_in_implementation false [get_files /scratch/qem/adam/development/fem-ii-embedded-system/Mars_ZX3_Reference_Design_for_FEMII/src/MarsZX3_FEMII.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top system_top -part xc7z020clg484-1
write_checkpoint -noxdef system_top.dcp
catch { report_utilization -file system_top_utilization_synth.rpt -pb system_top_utilization_synth.pb }
